# Generated by Django 5.0.3 on 2024-04-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='returns',
            field=models.ManyToManyField(blank=True, related_name='return_trans', to='inventory.returnitem'),
        ),
    ]
