# Generated by Django 5.0.3 on 2024-04-03 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_organization_slug_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
