# Generated by Django 5.0.3 on 2024-04-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loanable',
            field=models.BooleanField(default=True),
        ),
    ]
